# Generated by Django 5.1.2 on 2024-10-30 00:41
# This file is generated with the command in Terminal: 'python manage.py makemigrations'.
# This file will be executed with the command in Terminal: 'python manage.py migrate' and the result is the db file 'db.sqlite3'.


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("occupation", models.CharField(max_length=80)),
            ],
        ),
    ]
